### ISSUE TITLE
1.12.2 not working

### ISSUE THREAD

**Issue by pvprangergod** [MLG-Fortress/CustomItemRegistry#7]
hi im running paper spigot 1.12.2
the plugin worked on 1.14.3 but not 1.12.2, i get this in console on server start:

[15:58:53 INFO]: [CustomItemRecipes] Enabling CustomItemRecipes v1.4.6-3864c35
[15:58:53 ERROR]: Error occurred while enabling CustomItemRecipes v1.4.6-3864c35 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/inventory/RecipeChoice
        at com.robomwm.customitemrecipes.CustomItemRecipes.onEnable(CustomItemRecipes.java:57) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: org.bukkit.inventory.RecipeChoice
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        ... 12 more
[15:58:53 INFO]: [CustomItemRecipes] Disabling CustomItemRecipes v1.4.6-3864c35

**Comment by RoboMWM** [comment]
Use an older version to use an older version of spigot.

**Comment by RoboMWM** [comment]
https://dev.bukkit.org/projects/customitemrecipes/files?filter-status=1&filter-game-version=2020709689%3A6588
